import express from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || '0.0.0.0';

// Ensure uploads and data directories exist
const dataDir = path.resolve(__dirname, 'data');
const uploadsDir = path.resolve(__dirname, 'uploads');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir, { recursive: true });
}

const configFilePath = path.join(dataDir, 'settings.json');

// Helper to read persistent settings
const readSettings = () => {
  try {
    if (fs.existsSync(configFilePath)) {
      return JSON.parse(fs.readFileSync(configFilePath, 'utf-8'));
    }
  } catch (err) {
    console.error('Error reading settings:', err);
  }
  return {
    profilePhotoUrl: '',
    customLogoUrl: '',
    whatsAppNumber: '',
  };
};

// Helper to write persistent settings
const writeSettings = (settings) => {
  try {
    fs.writeFileSync(configFilePath, JSON.stringify(settings, null, 2), 'utf-8');
  } catch (err) {
    console.error('Error saving settings:', err);
  }
};

// Allow large image payloads (e.g. photos up to 25MB)
app.use(express.json({ limit: '25mb' }));
app.use(express.urlencoded({ extended: true, limit: '25mb' }));

// Serve static uploaded assets directly
app.use('/uploads', express.static(uploadsDir));

// Serve static assets generated by Vite build
const distPath = path.resolve(__dirname, 'dist');
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath));
}

// Public API endpoints for persistent multi-device settings
app.get('/api/settings', (_req, res) => {
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.json(readSettings());
});

app.post('/api/settings/photo', (req, res) => {
  try {
    const { imageBase64, filename } = req.body;
    if (!imageBase64) {
      return res.status(400).json({ error: 'Nenhuma imagem enviada.' });
    }

    // Match data:image/png;base64,...
    const matches = imageBase64.match(/^data:image\/([a-zA-Z0-9+]+);base64,(.+)$/);
    let ext = 'jpg';
    let dataBuffer;

    if (matches && matches.length === 3) {
      ext = matches[1] === 'jpeg' ? 'jpg' : matches[1];
      dataBuffer = Buffer.from(matches[2], 'base64');
    } else {
      dataBuffer = Buffer.from(imageBase64, 'base64');
    }

    // Save with predictable permanent name or timestamp
    const safeName = `autor_perfil_${Date.now()}.${ext}`;
    const destinationPath = path.join(uploadsDir, safeName);
    fs.writeFileSync(destinationPath, dataBuffer);

    // Also optionally copy as default author portrait
    const defaultAuthorPath = path.join(uploadsDir, 'autor_perfil.jpg');
    fs.writeFileSync(defaultAuthorPath, dataBuffer);

    const publicUrl = `/uploads/${safeName}`;
    const currentSettings = readSettings();
    currentSettings.profilePhotoUrl = publicUrl;
    currentSettings.lastUpdated = new Date().toISOString();
    writeSettings(currentSettings);

    return res.json({
      success: true,
      url: publicUrl,
      settings: currentSettings,
    });
  } catch (error) {
    console.error('Erro ao salvar foto:', error);
    return res.status(500).json({ error: 'Erro interno ao salvar arquivo no servidor.' });
  }
});

// Update WhatsApp or other global configs across devices
app.post('/api/settings', (req, res) => {
  try {
    const { whatsAppNumber, customLogoUrl } = req.body;
    const currentSettings = readSettings();

    if (whatsAppNumber !== undefined) currentSettings.whatsAppNumber = whatsAppNumber;
    if (customLogoUrl !== undefined) currentSettings.customLogoUrl = customLogoUrl;
    currentSettings.lastUpdated = new Date().toISOString();

    writeSettings(currentSettings);
    return res.json({ success: true, settings: currentSettings });
  } catch (error) {
    console.error('Erro ao atualizar configurações:', error);
    return res.status(500).json({ error: 'Erro ao atualizar dados.' });
  }
});

// Health check endpoint for reverse proxies (Nginx / Caddy / Traefik)
app.get('/health', (_req, res) => {
  res.status(200).json({ status: 'ok', service: 'millari-website', timestamp: new Date().toISOString() });
});

// SPA fallback: any other route returns index.html
app.get('*', (_req, res) => {
  const indexPath = path.join(distPath, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.send('Build em andamento ou aplicação carregando...');
  }
});

app.listen(PORT, HOST, () => {
  console.log(`[Millari Web] Servidor rodando em http://${HOST}:${PORT}`);
  console.log(`[Millari Web] Pasta de uploads persistentes: ${uploadsDir}`);
});
