import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || '0.0.0.0';

// Serve static assets generated by Vite build
const distPath = path.resolve(__dirname, 'dist');
app.use(express.static(distPath));

// Health check endpoint for reverse proxies (Nginx / Caddy / Traefik)
app.get('/health', (_req, res) => {
  res.status(200).json({ status: 'ok', service: 'millari-website', timestamp: new Date().toISOString() });
});

// SPA fallback: any other route returns index.html
app.get('*', (_req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

app.listen(PORT, HOST, () => {
  console.log(`[Millari Web] Servidor rodando em http://${HOST}:${PORT}`);
});
